name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        android-gradle-plugin: [4.1.0, 4.2.0, 7.0.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: gradle

      - name: Run checks
        env:
          ANDROID_GRADLE_PLUGIN_VERSION: ${{ matrix.android-gradle-plugin }}
        run: ./gradlew check --no-daemon --stacktrace
